// Generated by Wrangler on Tue Sep 17 2024 14:58:52 GMT+0200 (Central European Summer Time)
// by running `wrangler types`

interface Env {
	CONFIG_STORAGE: DurableObjectNamespace /* ConfigStorage from do-rl-worker */;
}
