// Generated by Wrangler on Mon Sep 16 2024 17:43:22 GMT+0200 (Central European Summer Time)
// by running `wrangler types`

interface Env {
	CONFIG_STORAGE: DurableObjectNamespace /* ConfigStorage from do-rl-worker */;
}
