name = "rate-limiter-configurator"
compatibility_date = "2024-08-21"

# This is required for Pages projects
pages_build_output_dir = "./dist"

[durable_objects]
bindings = [
  { name = "CONFIG_STORAGE", class_name = "ConfigStorage", script_name = "do-rl-worker" }
]
